CREATE DATABASE IF NOT EXISTS audio_service
CHARACTER SET utf8mb4 
COLLATE utf8mb4_unicode_ci;

CREATE TABLE audio_service.audio (
    id VARCHAR(128) NOT NULL,
    creator_id VARCHAR(128) NOT NULL,
    title VARCHAR(256) NOT NULL,
    file_url VARCHAR(2048) NOT NULL,
    version INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
    CONSTRAINT title_unique UNIQUE (creator_id, title)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;